### ISSUE TITLE
Modifies non-HTML files (e.g. CSS files)

### ISSUE THREAD

**Issue by eliotsykes** [manheim/metalsmith-jquery#3]
metalsmith-jquery modifies non-HTML files, such as stylesheets. Using [metalsmith-branch](https://github.com/ericgj/metalsmith-branch) is one workaround.

**Comment by eliotsykes** [comment]
Workaround code sample: 

```javascript
    .use(
      // Limit metalsmith-jquery to html files
      branch('*.html').use(
        jquery(function($) {
          $('pre').addClass("language-javascript");
        })
      )
    )
```

**Comment by pofallon** [comment]
That makes sense that we'd only want it to modify HTML, and your workaround seems reasonable in that case.  Is there value in enforcing this in the plugin itself?

**Comment by eliotsykes** [comment]
I think it'd be good to enforce the type of file processed in the plugin itself. I think this is the convention used by other plugins that are only intended for certain file types.

**Comment by pofallon** [comment]
You can now specify a pattern to match a set of files for jquery to process (see the README).  This will let you tell the jquery plugin to only process *.html files.
