### ISSUE TITLE
[question] Is there no way to get the metalsmith file object?

### ISSUE THREAD

**Issue by CharlesHolbrow** [manheim/metalsmith-jquery#4]
I want to modify the metalsmith metadata based on the html contents. Is there no way to do this inside the callback argument?

**Comment by CharlesHolbrow** [comment]
Here's a pull request for this feature:  https://github.com/manheim/metalsmith-jquery/pull/5

**Comment by CharlesHolbrow** [comment]
@pofallon could you take a look at this? Many thanks.

**Comment by pofallon** [comment]
Sure!  Can you add a test for it?  Thanks!

**Comment by CharlesHolbrow** [comment]
How's this: https://github.com/manheim/metalsmith-jquery/pull/5

**Comment by pofallon** [comment]
Looks good, thanks!

**Comment by pofallon** [comment]
Published to npm as v0.1.2, thanks again!
