### ISSUE TITLE
Cant add cheerio options

### ISSUE THREAD

**Issue by maraszczuk** [manheim/metalsmith-jquery#7]
I need to use characters not covered by basic latin alphabet. Those characters keep getting escaped when I use metalsmith-jquery, however the contents appear normal before the metalsmith-jquery module is run. This applies to all non-basic characters (such as żążółć) including japanese kana, chinese hanzi, korean hangul and various cyrillic scripts.

I attached a pull request that enables supplying cheerio loading options as the last parameter to metalsmith-jquery at #6

**Comment by pofallon** [comment]
Thanks for the patch!  New version published to npm as v0.2.2
